# Generated by Django 3.1.7 on 2021-03-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
